export const ONSUBMIT_ADD_PATIENT = 'ONSUBMIT_ADD_PATIENT';
export const ONBLUR_HANDLER = 'ONBLUR_HANDLER';
export const ONCHANGE_DATE_HANDLER = 'ONCHANGE_DATE_HANDLER';
export const ONCHANGE_SELECT_HANDLER = 'ONCHANGE_SELECT_HANDLER';
export const ONCHANGE_RADIO_HANDLER = 'ONCHANGE_RADIO_HANDLER';
export const ONCHANGE_CHECKBOX_HANDLER = 'ONCHANGE_CHECKBOX_HANDLER';
export const ONCLICK_POPUPOPEN_HANDLER = 'ONCLICK_POPUPOPEN_HANDLER';
export const ONCLICK_POPUPCLOSE_HANDLER = 'ONCLICK_POPUPCLOSE_HANDLER';



