export default {
    firstName: "",
    middleName: "",
    placeOfService: "",
    dateOfBirth: "",
    address1: "",
    zip: "",
    city: "",
    state: "",
    chartId: "",
    externalPatientId: "",
    martialStatus: "",
    employmentStatus: "",
    ethnicity: "",
    preferredLanguage: "",
    referredByPhysician: "",
    referringProvider: "",
    dateReferred: "",
    referringProviderCheckStatus : true,
    prefferedPhone :  "",
    homePhone :  "",
    workPhone :  "",
    cellPhone :   "",
    otherPhone :  "",
    email :   "",
    emergencyName :   "",
    emergencyRelationship :   "",
    emergencyPhoneNumber :   "",
    emergencyName2 :   "",
    emergencyRelationship2 :   "",
    patientTimeZone :   "",
    communicationPreferenceCall :  "",
    communicationPreferenceEmail :  "",
    communicationPreferenceSms :  "",
    allowSaturdayCommunication : "",
    allowSundayCommunication :   "",
}